using Godot;
using System.Collections.Generic;

namespace Beep.ECS.UI.Kit
{
    /// <summary>
    /// The kit's MATERIAL axis — the third one, and the one it shipped without.
    ///
    /// WHY THIS EXISTS
    /// ---------------
    /// The kit had a silhouette axis and a colour axis. Every plate was a flat fill, so ten
    /// genres differed only by outline and hue, and repeatedly read as "the same shapes, just
    /// different colours". `Example_Art/uitexturs.png` is the counter-example: nine tiles that
    /// share ONE rounded-square silhouette, same corner radius, same drop shadow, and are
    /// unmistakably nine different things — leather, rubber, glossy leaf, brushed metal,
    /// diamond plate, stone, wood plank, denim, graph paper. Measured on a colour- and
    /// scale-invariant detail axis they span 67x. The kit measured a flat zero.
    ///
    /// HOW IT WORKS
    /// ------------
    /// Each genre gets a tiling ALPHA MASK (RGB white, alpha = 1 - luminance) drawn inside the
    /// plate's own silhouette and modulated by a darkened plate colour. Because the mask holds
    /// no colour, one file reskins with every palette — the grain darkens the plate where the
    /// pattern is, and leaves it alone where it isn't.
    ///
    /// The assignment in <see cref="KitGrainTable"/> is GENERATED by
    /// tools/genre_shapes/pick_grain.py, which picks each pattern by measuring it against the
    /// material that genre's reference art is actually made of. Direction drives the choice
    /// (tiling cannot rotate a grain); tile count is solved so feature size matches; amplitude
    /// is solved so detail energy matches.
    ///
    /// Patterns are CC0 (Kenney Pattern Pack) — see textures/grain/LICENSE.txt. Example_Art is
    /// licensed Vecteezy reference used for measurement only; none of its pixels ship.
    /// </summary>
    public static class KitGrain
    {
        private const string Dir = "res://addons/beep_game_builder_cs/textures/grain/";

        private static readonly Dictionary<string, Texture2D?> _cache = new();
        private static readonly HashSet<string> _warned = new();

        /// <summary>The grain for a genre, or null when the genre declares none.</summary>
        public static KitGrainDef? For(string genre)
        {
            if (string.IsNullOrEmpty(genre)) return null;
            bool has = KitGrainTable.ByGenre.TryGetValue(genre, out var def);

            // A theme may override the material. Fields left unset inherit the generated
            // per-genre assignment, so a theme that only wants a lighter grain does not have to
            // restate the pattern.
            var g = KitGeometry.ForGenre(genre);
            bool over = g.GrainPattern.Length > 0 || g.GrainAmount >= 0f || g.GrainTiles > 0;
            if (!over) return has ? def : null;

            // KitGrainDef is a STRUCT, so a failed TryGetValue leaves a DEFAULT here, not null.
            // Returning that would give an unknown genre a grain with an empty pattern -- which
            // resolves to "grain_.png", warns, and renders flat. A genre with no table entry and
            // no pattern override still has no grain.
            string pattern = g.GrainPattern.Length > 0 ? g.GrainPattern : (has ? def.Pattern : "");
            if (pattern.Length == 0) return null;

            return new KitGrainDef(
                pattern,
                g.GrainAmount >= 0f ? g.GrainAmount : (has ? def.Amount : 0.3f),
                g.GrainTiles > 0 ? g.GrainTiles : (has ? def.Tiles : 2),
                // The table's material NAME describes the table's PATTERN. Once a theme
                // overrides the pattern the name no longer applies -- citybuilder/blueprint
                // reported "pattern_41 (stone)" while pattern_41 is graph paper, and that string
                // is shown in the style showcase. A wrong label is worse than no label.
                g.GrainPattern.Length > 0 ? "theme" : (has ? def.Material : "theme"));
        }

        /// <summary>The mask texture for a genre. Null (with ONE warning) when the file is
        /// missing — a silently absent grain is indistinguishable from a genre that never had
        /// one, which is exactly the class of defect this repo keeps paying for.</summary>
        public static Texture2D? Texture(string genre)
        {
            if (For(genre) is not { } def) return null;
            string path = $"{Dir}grain_{def.Pattern}.png";
            if (_cache.TryGetValue(path, out var cached)) return cached;

            Texture2D? tex = ResourceLoader.Exists(path) ? GD.Load<Texture2D>(path) : null;
            if (tex == null && _warned.Add(path))
            {
                GD.PushWarning(
                    $"[KitGrain] genre '{genre}' declares grain '{def.Pattern}' ({def.Material}) "
                    + $"but {path} is missing, so its plates will render FLAT — visually "
                    + "identical to every other genre with a missing grain. Regenerate with: "
                    + "python tools/genre_shapes/pick_grain.py --install");
            }
            _cache[path] = tex;
            return tex;
        }

        /// <summary>
        /// Paint the grain inside <paramref name="poly"/> on <paramref name="ci"/>.
        ///
        /// UVs are computed from the rect so the pattern tiles at the measured repeat count
        /// rather than stretching to fit — a stretched grain changes character with every
        /// widget size, which defeats the point of matching a feature size at all.
        /// </summary>
        public static void Draw(CanvasItem ci, string genre, Vector2[]? poly, Rect2 rect,
                                Color plate, float strength = 1f)
        {
            if (poly == null || poly.Length < 3) return;
            if (rect.Size.X < 2f || rect.Size.Y < 2f) return;
            if (For(genre) is not { } def) return;
            if (Texture(genre) is not { } tex) return;

            // Tiles are counted across the SHORT edge so a wide button and a tall panel get
            // the same physical grain size instead of the same number of stretched repeats.
            float shortEdge = Mathf.Min(rect.Size.X, rect.Size.Y);
            float tilePx = Mathf.Max(4f, shortEdge / Mathf.Max(1, def.Tiles));

            // TRIANGULATION GUARD. DrawColoredPolygon requires a SIMPLE polygon; the silhouettes
            // that deliberately break the rectangle do not always give one — Spiked emits points
            // outside the bounding rect and Torn uses non-parallel edges, and both made Godot log
            // "Invalid polygon data, triangulation failed" and then draw NOTHING. That would have
            // left rpg and survival — the two genres with the most distinctive material — as the
            // only flat plates in the set, silently.
            //
            // Falling back to the bounding rect keeps the material rather than dropping it. The
            // grain then squares off at the silhouette's edge, which is a small cosmetic loss
            // against losing the whole axis for those genres.
            if (Geometry2D.TriangulatePolygon(poly).Length == 0)
            {
                if (_warned.Add($"poly:{genre}"))
                    GD.PushWarning(
                        $"[KitGrain] genre '{genre}' has a silhouette Godot cannot triangulate "
                        + $"({poly.Length} points); drawing its grain clipped to the bounding rect "
                        + "instead. The material is preserved, the shaped clip is not.");
                poly = new[]
                {
                    rect.Position, rect.Position + new Vector2(rect.Size.X, 0),
                    rect.Position + rect.Size, rect.Position + new Vector2(0, rect.Size.Y),
                };
            }

            var uvs = new Vector2[poly.Length];
            for (int i = 0; i < poly.Length; i++)
                uvs[i] = (poly[i] - rect.Position) / tilePx;

            // UVs run past 1.0, so the canvas item must repeat rather than clamp. Without
            // this the pattern draws once in the corner and smears its edge pixel across the
            // rest of the plate.
            if (ci.TextureRepeat != CanvasItem.TextureRepeatEnum.Enabled)
                ci.TextureRepeat = CanvasItem.TextureRepeatEnum.Enabled;

            float a = Mathf.Clamp(def.Amount * strength, 0f, 1f);
            if (a < 0.004f) return;

            // The grain darkens toward the plate's own shadow rather than toward black, so a
            // pale parchment genre gets a warm grain and a dark metal one a cool grain, both
            // from the palette instead of from a literal.
            Color ink = new(plate.R * 0.35f, plate.G * 0.34f, plate.B * 0.38f, a);
            ci.DrawColoredPolygon(poly, ink, uvs, tex);
        }
    }
}
