// <auto-generated>
//     GENERATED by tools/genre_shapes/pick_grain.py -- do not edit by hand.
//     Regenerate with:  python tools/genre_shapes/pick_grain.py --install
//
//     Each genre's pattern is chosen by MEASUREMENT against the material its
//     reference art is made of (Example_Art/uitexturs.png), on three
//     colour- and scale-invariant axes: hf (detail energy), dir (grain
//     direction) and coarseness (feature size). Direction drives the choice
//     because tiling cannot fix it; tile count is then solved so the feature
//     size matches the reference material, and amplitude so the detail energy
//     does. Patterns are CC0 (Kenney Pattern Pack); see textures/grain/LICENSE.txt.
// </auto-generated>
using System.Collections.Generic;

namespace Beep.ECS.UI.Kit
{
    /// <summary>One genre's grain: which mask, how strongly, how many repeats.</summary>
    public readonly record struct KitGrainDef(string Pattern, float Amount,
                                              int Tiles, string Material);

    /// <summary>The measured genre -> grain assignment.</summary>
    public static class KitGrainTable
    {
        public static readonly IReadOnlyDictionary<string, KitGrainDef> ByGenre =
            new Dictionary<string, KitGrainDef>
        {
            ["cardgame"] = new("pattern_57", 0.300f, 5, "denim"),
            ["citybuilder"] = new("pattern_78", 0.136f, 2, "stone"),
            ["platformer"] = new("pattern_58", 0.300f, 1, "rubber-dots"),
            ["puzzle"] = new("pattern_41", 0.300f, 2, "graph-paper"),
            ["racing"] = new("pattern_37", 0.300f, 1, "brushed-metal"),
            ["rpg"] = new("pattern_50", 0.300f, 3, "wood-plank"),
            ["shooter"] = new("pattern_08", 0.300f, 4, "diamond-plate"),
            ["strategy"] = new("pattern_78", 0.136f, 4, "stone"),
            ["survival"] = new("pattern_49", 0.300f, 4, "leather"),
            ["topdown"] = new("pattern_19", 0.293f, 2, "glossy-leaf"),
        };
    }
}
