using Godot;
using System.Collections.Generic;

namespace Beep.GameBuilder
{
    /// <summary>
    /// Stamps a new genre screen that already obeys every convention this repo enforces,
    /// instead of leaving them to be rediscovered (and reviewed) each time:
    ///
    ///  • an opaque KitColorRect named "Background", so ThemePresetComponent paints it from bg_canvas;
    ///  • a kit-composed header whose title carries <c>theme_type_variation = &amp;"BeepTitle"</c>, an accent rule,
    ///    and a back button with a real height (120×44 — a 0-height button was the shipped default);
    ///  • ThemePresetComponent parented to the CONTENT Control with the right GenreName;
    ///  • GameInfoBinder bound to the title;
    ///  • PascalCase [Export] names, which Godot silently drops when written snake_case;
    ///  • a C# script resolving its button with <c>ConnectButton("BackButton", …)</c> — by NAME, so a
    ///    later restyle that inserts a wrapper cannot kill it.
    ///
    /// EDITOR ONLY: writes into res://.
    /// </summary>
    public static class BeepScreenGenerator
    {
        /// <summary>Create <c>res://scenes/ui/&lt;genre&gt;/&lt;snake_name&gt;.tscn</c> and its script.
        /// Returns a log; nothing is overwritten unless <paramref name="overwrite"/> is set.</summary>
        public static List<string> CreateScreen(string genreId, string screenName, string title, bool overwrite = false)
        {
            var log = new List<string>();
            if (string.IsNullOrWhiteSpace(screenName)) { log.Add("✗ screen name is required"); return log; }

            string cls = ToPascal(screenName);
            string snake = ToSnake(cls);
            if (string.IsNullOrEmpty(cls)) { log.Add($"✗ '{screenName}' has no usable letters for a class name"); return log; }
            if (string.IsNullOrWhiteSpace(title)) title = Humanise(cls);

            string scriptDir = $"res://scripts/screens/{genreId}";
            string sceneDir = $"res://scenes/ui/{genreId}";
            BeepFileUtils.EnsureDir(scriptDir);
            BeepFileUtils.EnsureDir(sceneDir);

            string scriptPath = $"{scriptDir}/{cls}.cs";
            string scenePath = $"{sceneDir}/{snake}.tscn";

            if (BeepFileUtils.SafeWriteText(scriptPath, ScriptSource(cls), overwrite)) log.Add($"✓ {scriptPath}");
            else log.Add($"· {scriptPath} exists — kept");

            if (BeepFileUtils.SafeWriteText(scenePath, SceneSource(cls, snake, title, genreId, scriptPath), overwrite)) log.Add($"✓ {scenePath}");
            else log.Add($"· {scenePath} exists — kept");

            log.Add("→ Build the project so Godot registers the new script, then open the scene.");
            return log;
        }

        private static string ScriptSource(string cls) =>
$@"using Godot;
using Beep.ECS;
using Beep.ECS.Scenes;

/// <summary>Generated by Beep. Wire this screen's own controls here.</summary>
[Tool]
[GlobalClass]
public partial class {cls} : Control
{{
    public override void _Ready()
    {{
        if (Engine.IsEditorHint()) return;

        // Resolve by NAME, never by path: a path bakes in the layout, so inserting one wrapper
        // container later silently kills every button under it.
        this.ConnectButton(""BackButton"", () => UI.SceneNav.CloseOrReturn(this, GameApp.Instance?.GameScenePath));
    }}
}}
";

        private static string SceneSource(string cls, string snake, string title, string genreId, string scriptPath) =>
$@"[gd_scene load_steps=7 format=3]

[ext_resource type=""Script"" path=""res://addons/beep_game_builder_cs/ecs/ui/ThemePresetComponent.cs"" id=""1_theme""]
[ext_resource type=""Script"" path=""res://addons/beep_game_builder_cs/ecs/ui/GameInfoBinder.cs"" id=""2_binder""]
[ext_resource type=""Script"" path=""{scriptPath}"" id=""3_script""]
[ext_resource type=""Script"" path=""res://addons/beep_game_builder_cs/ecs/ui/kit/KitColorRect.cs"" id=""k_color""]
[ext_resource type=""Script"" path=""res://addons/beep_game_builder_cs/ecs/ui/kit/KitLabel.cs"" id=""k_label""]
[ext_resource type=""Script"" path=""res://addons/beep_game_builder_cs/ecs/ui/kit/KitPushButton.cs"" id=""k_pbtn""]
[ext_resource type=""Script"" path=""res://addons/beep_game_builder_cs/ecs/ui/kit/KitPanelContainer.cs"" id=""k_panel""]

[node name=""{cls}"" type=""Control""]
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
grow_horizontal = 2
grow_vertical = 2
script = ExtResource(""3_script"")

[node name=""Background"" type=""ColorRect"" parent="".""]
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
grow_horizontal = 2
grow_vertical = 2
color = Color(0.08, 0.08, 0.11, 1)
script = ExtResource(""k_color"")

[node name=""Margin"" type=""MarginContainer"" parent="".""]
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
grow_horizontal = 2
grow_vertical = 2
theme_override_constants/margin_left = 40
theme_override_constants/margin_right = 40
theme_override_constants/margin_top = 28
theme_override_constants/margin_bottom = 28

[node name=""VBox"" type=""VBoxContainer"" parent=""Margin""]
theme_override_constants/separation = 20

[node name=""Header"" type=""HBoxContainer"" parent=""Margin/VBox""]
theme_override_constants/separation = 16

[node name=""TitleLabel"" type=""Label"" parent=""Margin/VBox/Header""]
theme_type_variation = &""BeepTitle""
text = ""{title}""
size_flags_horizontal = 3
vertical_alignment = 1
script = ExtResource(""k_label"")

[node name=""BackButton"" type=""Button"" parent=""Margin/VBox/Header""]
custom_minimum_size = Vector2(120, 44)
text = ""< Back""
script = ExtResource(""k_pbtn"")

[node name=""HeaderRule"" type=""HSeparator"" parent=""Margin/VBox""]

[node name=""Body"" type=""PanelContainer"" parent=""Margin/VBox""]
size_flags_vertical = 3
script = ExtResource(""k_panel"")

[node name=""BodyMargin"" type=""MarginContainer"" parent=""Margin/VBox/Body""]
theme_override_constants/margin_left = 20
theme_override_constants/margin_right = 20
theme_override_constants/margin_top = 16
theme_override_constants/margin_bottom = 16

[node name=""BodyVBox"" type=""VBoxContainer"" parent=""Margin/VBox/Body/BodyMargin""]
theme_override_constants/separation = 14

[node name=""BodyHeading"" type=""Label"" parent=""Margin/VBox/Body/BodyMargin/BodyVBox""]
theme_type_variation = &""BeepSubtitle""
text = ""Section""
script = ExtResource(""k_label"")

[node name=""BodyCaption"" type=""Label"" parent=""Margin/VBox/Body/BodyMargin/BodyVBox""]
theme_type_variation = &""BeepCaption""
text = ""Replace this with the screen's content.""
script = ExtResource(""k_label"")

[node name=""BodySpacer"" type=""Control"" parent=""Margin/VBox/Body/BodyMargin/BodyVBox""]
size_flags_vertical = 3

[node name=""Theme"" type=""Node"" parent="".""]
script = ExtResource(""1_theme"")
GenreName = ""{genreId}""

[node name=""GameInfoBinder"" type=""Node"" parent="".""]
script = ExtResource(""2_binder"")
TitleLabelPath = NodePath(""Margin/VBox/Header/TitleLabel"")
AppendGameName = true
ThemeComponentPath = NodePath(""Theme"")
";

        // ── name helpers ──

        /// <summary>"race results" / "race_results" / "RaceResults" → "RaceResults".</summary>
        private static string ToPascal(string raw)
        {
            var sb = new System.Text.StringBuilder();
            bool up = true;
            foreach (char ch in raw)
            {
                if (char.IsLetterOrDigit(ch)) { sb.Append(up ? char.ToUpperInvariant(ch) : ch); up = false; }
                else up = true;
            }
            return sb.ToString();
        }

        /// <summary>"RaceResults" → "race_results".</summary>
        private static string ToSnake(string pascal)
        {
            var sb = new System.Text.StringBuilder();
            for (int i = 0; i < pascal.Length; i++)
            {
                if (i > 0 && char.IsUpper(pascal[i])) sb.Append('_');
                sb.Append(char.ToLowerInvariant(pascal[i]));
            }
            return sb.ToString();
        }

        /// <summary>"RaceResults" → "Race Results", for a default screen title.</summary>
        private static string Humanise(string pascal)
        {
            var sb = new System.Text.StringBuilder();
            for (int i = 0; i < pascal.Length; i++)
            {
                if (i > 0 && char.IsUpper(pascal[i])) sb.Append(' ');
                sb.Append(pascal[i]);
            }
            return sb.ToString();
        }
    }
}
